// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Xenko Shader Mixin Code Generator.
// To generate it yourself, please install Xenko.VisualStudio.Package .vsix
// and re-save the associated .xkfx.
// </auto-generated>

using System;
using Xenko.Core;
using Xenko.Rendering;
using Xenko.Graphics;
using Xenko.Shaders;
using Xenko.Core.Mathematics;
using Buffer = Xenko.Graphics.Buffer;

namespace Xenko.Rendering.Skyboxes
{
    public static partial class IsotropicVoxelColorKeys
    {
        public static readonly ValueParameterKey<float> MipCount = ParameterKeys.NewValue<float>();
        public static readonly ObjectParameterKey<Texture> VoxelVolume = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<Texture> VoxelVolumeR1 = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<Texture> VoxelVolumeR2 = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<Texture> VoxelVolumeR3 = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<Texture> VoxelVolumeR4 = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<Texture> VoxelVolumeR5 = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<Texture> VoxelVolumeR6 = ParameterKeys.NewObject<Texture>();
    }
}
